//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContextAccessor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContextAccessor.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap CAFUNC_BITMAP {
            get {
                object obj = ResourceManager.GetObject("CAFUNC_BITMAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows access to the context from within a map.
        /// </summary>
        internal static string CAFUNC_DESC {
            get {
                return ResourceManager.GetString("CAFUNC_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Accesor.
        /// </summary>
        internal static string CAFUNC_NAME {
            get {
                return ResourceManager.GetString("CAFUNC_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows access to the context from within a map.
        /// </summary>
        internal static string CAFUNC_TOOLTIP {
            get {
                return ResourceManager.GetString("CAFUNC_TOOLTIP", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CCFUNC_BITMAP {
            get {
                object obj = ResourceManager.GetObject("CCFUNC_BITMAP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to count the available context items.
        /// </summary>
        internal static string CCFUNC_DESC {
            get {
                return ResourceManager.GetString("CCFUNC_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Counter.
        /// </summary>
        internal static string CCFUNC_NAME {
            get {
                return ResourceManager.GetString("CCFUNC_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to count the available context items.
        /// </summary>
        internal static string CCFUNC_TOOLTIP {
            get {
                return ResourceManager.GetString("CCFUNC_TOOLTIP", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon CPC_ICON {
            get {
                object obj = ResourceManager.GetObject("CPC_ICON", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
